### ISSUE TITLE
can't seem to reach the openvino_detection_api on my dev env

### ISSUE THREAD

**Issue by raouln97** [BMW-InnovationLab/BMW-Anonymization-API#5]
i tried starting it on local and it works well but get an error in hosted environments

this is the error i get:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 800, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='openvino_segmentation_api', port=80): Max retries exceeded with url: /models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe23831ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by JMT800** [comment]
Hello @raouln97, apologies for the late reply.

Can you please provide more information regarding your setup:
- are you deploying the inference API as well as the anonymization API on the same machine or on separate machines?
- can you please provide more information regarding the hosted environment (which os, hw architecture,...)
- can you also please refer to which readme file you are following (as we have one for deploying all the solutions together via docker-compose or deploying them as standalone apis)

thanks in advance,
cheers
